title: ByteScribble
author: Hritik Kumar
email: hritikkumar.rd@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  ByteScribble is place where you can find insightful articles and comprehensive 
  guides on software architecture, system design, and interview preparation.
  Whether you're a seasoned developer, an aspiring architect, or someone preparing for technical
  interviews, you'll find valuable content tailored to help you succeed in your career.
slogan: >- # this means to ignore newlines until "baseurl:"
  Let's join our hand and build a community of tech enthusiasts and professionals as
  we scribble our way through the fascinating world of software development.
  Stay ahead of the curve with ByteScribble!
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: "@43ba76670139474"
github_username:  Hrtkk
plugins:
  - jekyll-feed
  - jekyll-remote-theme
markdown: kramdown
sass:
  sass_dir: assets/css
defaults:
  - 
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
      excerpt_separator: <!--more-->
      category: blogs
